---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adkgkgrj/cheque-bounce-advisor/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt