---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adkgkgrj/cheque-bounce-advisor/
    - /bin/cp -R . $DEPLOYPATH
    - source /home/adkgkgrj/nodevenv/cheque-bounce-advisor/20/bin/activate && cd $DEPLOYPATH && npm install
    - source /home/adkgkgrj/nodevenv/cheque-bounce-advisor/20/bin/activate && cd $DEPLOYPATH && npm run build -- --webpack
    - /bin/touch $DEPLOYPATH/tmp/restart.txt